# Generated by Django 2.2 on 2020-12-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201203_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.Blood'),
        ),
    ]
